baseURL = 'https://naknaknak.github.io/hugo/'
languageCode = 'en-us'
title = "Naknaknak's blog"
theme = 'm10c'
publishDir = 'docs'
canonifyurls = true
[params]
    author = 'naknaknak'
    description = 'none'